### PR TITLE
Enh#123

### LINKED ISSUE #123: TravisCI test for ENH#95
In #95 test-dataset was prepared by @Setnea This issue is for the test preparation without the need for working on the same branch.

### PR DESCRIPTION
**Pull request by dizak**
Closes #123 #95

### CODE REVIEW

**Comment by dizak** [comment]
True and agreed. That's why no numerical values are checked. For the ```*shared``` files, it's just two first columns - containing the label and group names. As for the ```*cons.tax.summary``` files - it's just three first columns - containing ```taxlevel```, ```rankID``` and ```taxon``` columns.

Was the taxonomical structure - not proportions - changed during your tests?

**Comment by Setnea** [comment]
No, but I only run a few simulations and it could be just a matter of luck.
We don't remove singletons or doubletons and our database is limited, moreover, even for the example provided for the testing purpose, we have taxons that are represented by only one OTU. I believe it is possible to get this very one sequence assigned slightly differentially (especially that some of them are not being classified to specific genus).
Since the taxon structure in *cons.tax.summary represents only the taxonomy of existing OTU, I think it would be safer to check only for the existence of higher, most likely present taxon levels such as phylum, class, maybe order. This approach should be also less vulnerable to possible changes in classify methods.

**Comment by dizak** [comment]
Out of 100 runs - the ```cons.tax.summary``` file differed from the reference.

**Comment by dizak** [comment]
Added condition to the ```awk``` test - nothing above the ```taxlevel == 3``` is displayed.

**Comment by Setnea** [comment]
Mm, cutoff on phylum level seems very safe. 
Good job!

**Pull request merged**
