### PR TITLE
165 citation in report

### PR DESCRIPTION
**Pull request by Setnea**
Adding request for citing at the end of the final HTML report file.

### CODE REVIEW

**Comment by Setnea** [comment]
@dizak I temporary included  'cat <html_report>' in travis build in order to track changes in the final image of the report, but I'm not sure if we want to keep it there forever. It makes log quite messy!
Should I remove it just before branch merge?

**Comment by dizak** [comment]
Yes, please remove the debug ```cat```.
For the rest - looks good to me :)

**Comment by Setnea** [comment]
I removed cat, branch is ready for merge, just waiting for your review.

**Comment by Setnea** [comment]
Closes #167

**Pull request merged**
