### PR TITLE
Enh#102

### LINKED ISSUE #102: Remove singletons
# enhancement
Add option to remove singletons/ OTUs with a smaller count number then the specific threshold.

### PR DESCRIPTION
**Pull request by Setnea**
Introduces mothur option to remove OTU with abundance lower/equal to a specific treshold. 
Fixes test and their results accordingly.

Closes #102

### CODE REVIEW

**Comment by Setnea** [comment]
Close due to problems with python 3.4

**Comment by dizak** [comment]
I see Python3.4 check failed during the preliminary steps. Restarted it for you.

**Comment by dizak** [comment]
Actually, I am tired of Python3.4 errors and 10 minutes runs @TravisCI just because of pandas compilation.  If this will not go fine this time we will abandon Python3.4 support.

**Comment by Setnea** [comment]
Thanks :) I removed 3.4 as requested. It was really annoying.

**Pull request merged**
